### ISSUE TITLE
When tapping on MGLSymbolStyleAnnotation the weird default icon is shown behind it 

### ISSUE THREAD

**Issue by TarasOsiris** [mapbox/mapbox-annotation-extension#68]
I have created a simple MGLSymbolStyleAnnotation with an icon image, but when this annotation is selected it animates some default icon which I can't figure out where it comes from. How do I get rid of this icon behind?

![image](https://user-images.githubusercontent.com/3141378/82942737-1a6b1d80-9fa1-11ea-9343-92ddef4ba8bc.png)

**Comment by captainbarbosa** [comment]
@TarasOsiris This is a known issue - you'll need to pass an `MGLAnnotationView` in the implementation for `mapView(_ mapView:viewFor annotation:)` as we do [in the demo app here](https://github.com/mapbox/mapbox-annotation-extension/blob/master/annotationapp/Controllers/MapViewController.swift#L125-L130): 

```swift
extension MapViewController: MGLMapViewDelegate {
    // This is required in order to hide the default Maps SDK pin
    func mapView(_ mapView: MGLMapView, viewFor annotation: MGLAnnotation) -> MGLAnnotationView? {
        return MGLAnnotationView(frame: CGRect(x: 0, y: 0, width: 10, height: 10))
    }
}
```

**Comment by TarasOsiris** [comment]
@captainbarbosa Thanks for the swift response! I see.
