### ISSUE TITLE
MGLPolygonStyleAnnotation coordinates do not conform to the GeoJSON spec

### ISSUE THREAD

**Issue by TimothySealy** [mapbox/mapbox-annotation-extension#70]
According to the GeoJSON spec the coordinates of a Polygon "MUST be an array of linear ring coordinate arrays". This translates to an array of arrays of points. According to the [example](https://docs.mapbox.com/ios/api/annotation-extension/0.0.1-beta.1/Classes/MGLPolygonStyleAnnotation.html) you have to pass an array of points to the `MGLPolygonStyleAnnotation`. It seems to be missing an additional (outer) array. 

Source: [https://tools.ietf.org/html/rfc7946#section-3.1.6](https://tools.ietf.org/html/rfc7946#section-3.1.6)

**Comment by skreborn** [comment]
`MGLPolygonStyleAnnotation` seems to have a constructor ([declaration](https://github.com/mapbox/mapbox-annotation-extension/blob/master/MapboxAnnotationExtension/Annotations/MGLPolygonStyleAnnotation.h#L61), [definition](https://github.com/mapbox/mapbox-annotation-extension/blob/master/MapboxAnnotationExtension/Annotations/MGLPolygonStyleAnnotation.m#L34-L40)) that accepts interior polygons (holes) as a separate parameter. Perhaps that is what you're looking for?

```
(instancetype)initWithCoordinates:(const CLLocationCoordinate2D *)coordinates count:(NSUInteger)count interiorPolygons:(NSArray<MGLPolygonFeature *> *)interiorPolygons
```

**Comment by TimothySealy** [comment]
@skreborn Thanks for the clarification. I overlooked the `interiorPolygons` parameter.

**Comment by skreborn** [comment]
Happy to help. Should this issue be closed then?

**Comment by TimothySealy** [comment]
Closing this up with two remarks:
1. I think it would be a good idea to clarify the usage of the interior polygons in the documentation.
2. A constructor overload which only takes polygons (where the first polygon is the outer and the rest inner polygons) would be appreciated.
