### ISSUE TITLE
Not able to display a circle annotation 

### ISSUE THREAD

**Issue by dsouzax** [mapbox/mapbox-annotation-extension#71]
I'm working on a project in college where I am trying to display some circle annotations. Have been able to show the default annotations which are available. Have been trying to change it to a circle but haven't been successful. Can anyone help ?

**Comment by captainbarbosa** [comment]
@dsouzax Have a look at the example included with this project, it illustrates how to add all annotations types (including a circle): https://github.com/mapbox/mapbox-annotation-extension/blob/master/annotationapp/Controllers/MapViewController.swift#L51-L62

Hope this helps.
